- name: Configure AAA and TACACS on Cisco devices
  hosts: all
  gather_facts: no

  tasks:
    - name: Get rendered configuration from NetBox
      uri:
        url: "http://192.168.1.178:8000/api/dcim/devices/{{ inventory_hostname }}/config-context/"
        method: GET
        headers:
          Authorization: "Token {{ netbox_api_token }}"
          Content-Type: "application/json"
      register: netbox_config

    - name: Extract configuration from NetBox response
      set_fact:
        rendered_config: "{{ netbox_config.json.rendered_config }}"

    - name: Deploy configuration to Cisco device
      ios_config:
        lines: "{{ rendered_config.splitlines() }}"
      vars:
        ansible_host: "{{ ansible_host | default(hostvars[inventory_hostname]['primary_ip4']) }}"
