---
- name: Backup configuration
  hosts: all
  gather_facts: no

  tasks:
    - name: Run show running-config on remote devices
      ios_command:
        commands: "show running-config"
      register: config

    - name: Ensure backup folder is created
      file:
        path: "{{ backup_root }}"
        state: directory
      run_once: yes

    - name: Ensure device folder is created
      file:
        path: "{{ backup_root }}/{{ inventory_hostname }}"
        state: directory

    - name: Get timestamp
      command: date +%Y%m%d
      register: timestamp
      delegate_to: localhost

    - name: Get/copy backup
      copy:
        content: "{{ config.stdout[0] }}"
        dest: "{{ backup_root }}/{{ inventory_hostname }}/running-config_{{ timestamp.stdout }}"
