---

- name: "First Play: Automate Routing Configs using Jinja2"
  hosts: core_routers
  connection: network_cli
  gather_facts: false
  tasks:
    - name: "First Task: Identify Correct Jinja Template"
      set_fact:
        eigrp_path: "templates/{{ device_type }}_eigrp.j2"

    - name: "Second Task: Source Template & Apply Configs!"
      cli_config:
        config: "{{ lookup('template', eigrp_path) }}"
      notify: config_changed
      register: response
  

  handlers:
    - name: "Output Changes..."
      listen: config_changed
      debug:
        msg: "{{ response }}"

