---
- name: Gather facts from Cisco IOS-XE device
  hosts: platforms_cisco-ios-xe
  gather_facts: no

  tasks:
    - name: Gather IOS facts
      cisco.ios.ios_facts:
        gather_subset: all

    - name: Display gathered facts
      debug:
        var: ansible_facts
