---
- hosts: core_routers
  gather_facts: yes
  ignore_errors: yes

  tasks:
    - name: obtain YAML file
      include_vars: vars/{{ inventory_hostname }}.yml
    
    - name: Render Template
      template:
        src: templates/device_configs.j2
        dest: Results/"{{ inventory_hostname }}.txt"

#    - name: IOS Based Configuration for {{ inventory_hostname }}.
#      ios_config:
#        src: templates/device_configs.j2
#        save_when: modified