---
- name: AWX Deploy Cisco Switch Configuration from NetBox
  hosts: platforms_cisco-ios-xe
  connection: network_cli
  ansible_network_os: cisco.ios.ios
  gather_facts: yes

  tasks:
    - name: Pull rendered config from NetBox
      uri:
        url: "http://netbox.local/api/dcim/devices/{{ inventory_hostname }}/render-config/"
        method: GET
        headers:
          Authorization: "Token {{ netbox_api_token }}"
        return_content: yes
      register: netbox_config

    - name: Save rendered config to a temporary file
      copy:
        content: "{{ netbox_config.content }}"
        dest: "/tmp/{{ inventory_hostname }}_config.txt"

    - name: Deploy configuration to Cisco switch
      cisco.ios.ios_config:
        src: "/tmp/{{ inventory_hostname }}_config.txt"
        save_when: always

    - name: Save running config to startup config
      cisco.ios.ios_command:
        commands:
          - write memory
