---
- name: Pull Rendered Config from NetBox and Push to Cisco Switch
  hosts: all
  gather_facts: no
  vars:
    netbox_api_url: "http://192.168.1.178:8000/api/"
    netbox_api_token: "{{ netbox_api_token }}"  # Passed as an extra var
  tasks:

    - name: Get device details from NetBox
      uri:
        url: "{{ netbox_api_url }}dcim/devices/?name={{ inventory_hostname }}"
        method: GET
        headers:
          Authorization: "Token {{ netbox_api_token }}"
          Content-Type: "application/json"
        return_content: yes
        status_code: 200
      register: netbox_device_response

    - name: Extract primary IP from NetBox
      set_fact:
        device_ip: "{{ netbox_device_response.json.results[0].primary_ip4.address.split('/')[0] | default('') }}"

    - name: Debug - Show device IP
      debug:
        msg: "Device IP for {{ inventory_hostname }}: {{ device_ip }}"

    - name: Get rendered config from NetBox
      uri:
        url: "{{ netbox_api_url }}extras/rendered-templates/?device={{ inventory_hostname }}"
        method: GET
        headers:
          Authorization: "Token {{ netbox_api_token }}"
          Content-Type: "application/json"
        return_content: yes
        status_code: 200
      register: netbox_config_response

    - name: Extract rendered config
      set_fact:
        rendered_config: "{{ netbox_config_response.json.results[0].rendered | default('') }}"

    - name: Debug - Show rendered config
      debug:
        msg: "{{ rendered_config }}"

    - name: Save rendered config to a local file
      copy:
        content: "{{ rendered_config }}"
        dest: "/tmp/{{ inventory_hostname }}.cfg"

    - name: Ensure SSH connection to the switch
      wait_for:
        host: "{{ device_ip }}"
        port: 22
        timeout: 10

    - name: Push config to the switch
      ios_config:
        host: "{{ device_ip }}"
        username: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        transport: cli
        lines: "{{ rendered_config.splitlines() }}"

    - name: Save config to memory
      ios_command:
        host: "{{ device_ip }}"
        username: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        commands:
          - "write memory"
