---
- name: Fetch Rendered Config from NetBox and Apply to Cisco Switch
  hosts: all
  gather_facts: no
  tasks:
    - name: Fetch rendered configuration from NetBox
      uri:
        url: "http://{{ netbox_host }}/api/dcim/devices/{{ inventory_hostname }}/render-config/"
        method: POST
        headers:
          Authorization: "Token {{ netbox_api_token }}"
        return_content: yes
      register: netbox_rendered_config

    - name: Extract configuration content from NetBox response
      set_fact:
        rendered_config: "{{ netbox_rendered_config.json.content }}"
      when: netbox_rendered_config is defined

    - name: Debug - Display rendered configuration
      debug:
        msg: "{{ rendered_config }}"

    - name: Push configuration to Cisco switch
      cisco.ios.ios_config:
        lines: "{{ rendered_config.splitlines() }}"
        save_when: modified
      vars:
        ansible_user: "{{ ansible_user }}"
        ansible_password: "{{ ansible_password }}"
        ansible_become: yes
        ansible_become_password: "{{ ansible_enable_password }}"
      when: rendered_config is defined
