---
- name: Deploy Base Config from NetBox to Cisco Switches
  hosts: platforms_cisco-ios-xe
  gather_facts: no
  connection: network_cli
  become: yes
  become_method: enable

  vars:
    netbox_url: "http://192.168.1.178:8000/extras/config-templates"
    netbox_token: "205ae3d78a1fb30a6fddbdaf9f6e6a3cead9be7d"

  tasks:
    - name: Get the base-config template from NetBox
      uri:
        url: "{{ netbox_url }}?name=base-config"
        headers:
          Authorization: "Token {{ netbox_token }}"
          Content-Type: "application/json"
        method: GET
        return_content: yes
      register: netbox_template

    - name: Extract and render the base-config template
      set_fact:
        switch_config: "{{ netbox_template.json.results[0].template }}"

    - name: Deploy configuration to Cisco switch
      ios_config:
        lines: "{{ switch_config.split('\n') }}"
        save_when: always

    - name: Verify deployed configuration
      ios_command:
        commands:
          - show running-config
      register: running_config

    - name: Display running configuration
      debug:
        var: running_config.stdout_lines
