---
- name: Fetch Rendered Config from NetBox and Apply to Cisco Switch
  hosts: all
  gather_facts: no
  tasks:
    - name: Get rendered configuration from NetBox
      uri:
        url: "{{ netbox_device_url }}"
        method: POST
        headers:
          Authorization: "Token {{ netbox_api_token }}"
          Content-Type: "application/json"
        return_content: yes
        status_code: 200
      register: netbox_rendered_config

    - name: Extract configuration content from NetBox response
      set_fact:
        rendered_config: "{{ netbox_rendered_config.json.content.splitlines() }}"  # Directly split to list of lines

    - name: Debug - Display rendered configuration
      debug:
        msg: "{{ rendered_config }}"

    - name: Push configuration to Cisco switch
      cisco.ios.ios_config:
        lines: "{{ rendered_config }}"  # No need to split again as it's already a list
        save_when: modified  # Save the configuration only if modified
