---
- name: Pull Rendered Config from NetBox and Push to Cisco Switch
  hosts: all
  gather_facts: no
  vars:
    netbox_api_token: "{{ netbox_api_token }}"  # Passed as an extra var in AWX
    netbox_url: "http://192.168.1.178:8000"
    output_dir: "/tmp"

  tasks:

    - name: Fetch Rendered Configuration from NetBox
      uri:
        url: "{{ netbox_url }}/api/dcim/devices/?name={{ inventory_hostname }}&include=config_rendered"
        method: GET
        headers:
          Authorization: "Token {{ netbox_api_token }}"
          Content-Type: "application/json"
        return_content: yes
        status_code: 200
      register: netbox_config_response

    - name: Extract Rendered Configuration
      set_fact:
        rendered_config: "{{ netbox_config_response.json.results[0].config_rendered | default('') }}"

    - name: Debug - Show Rendered Config
      debug:
        msg: "{{ rendered_config }}"
      when: rendered_config | length > 0

    - name: Save Rendered Config to File for Reference
      copy:
        content: "{{ rendered_config }}"
        dest: "{{ output_dir }}/{{ inventory_hostname }}.cfg"
        mode: "0644"
      when: rendered_config | length > 0

    - name: Push Config to Cisco Switch
      cisco.ios.ios_config:
        lines: "{{ rendered_config.splitlines() }}"
      when: rendered_config | length > 0
      vars:
        ansible_connection: network_cli
        ansible_network_os: ios
        ansible_user: "{{ lookup('env', 'ANSIBLE_NET_USERNAME') }}"
        ansible_password: "{{ lookup('env', 'ANSIBLE_NET_PASSWORD') }}"
        ansible_become: yes
        ansible_become_method: enable

    - name: Save Configuration (Write Memory)
      cisco.ios.ios_command:
        commands:
          - "write memory"
      when: rendered_config | length > 0
      vars:
        ansible_connection: network_cli
        ansible_network_os: ios
        ansible_user: "{{ lookup('env', 'ANSIBLE_NET_USERNAME') }}"
        ansible_password: "{{ lookup('env', 'ANSIBLE_NET_PASSWORD') }}"
        ansible_become: yes
        ansible_become_method: enable
