---
- name: Generate Device Configuration
  hosts: platforms_cisco-ios
  gather_facts: True
  connection: network_cli
  vars:
     ansible_network_os: ios

  roles:
    - role: generate_config
      tags: generate_config
