---
- name: Generate Device Configuration
  hosts: primary_ip4_10.10.10.10
  gather_facts: True
  connection: network_cli
  vars:
     ansible_network_os: ios

  roles:
    - role: generate_config
      tags: generate_config